In [1]:
import pandas as pd
import glob
import time
import duckdb

In [2]:
conn = duckdb.connect()

In [3]:
# with duckdb
cur_time = time.time()
df = conn.execute("""
	SELECT *
	FROM 'Sales_Product_Combined.csv'
	LIMIT 10
""").df()
print(f"time: {(time.time() - cur_time)}")
print(df)

time: 0.10766410827636719
   Order ID                     Product  Quantity Ordered     Price  \
0    176558        USB-C Charging Cable                 2     11.95
1    176559  Bose SoundSport Headphones                 1     99.99
2    176560                Google Phone                 1       600
3    176560            Wired Headphones                 1     11.99
4    176561            Wired Headphones                 1     11.99
5    176562        USB-C Charging Cable                 1     11.95
6    176563  Bose SoundSport Headphones                 1     99.99
7    176564        USB-C Charging Cable                 1     11.95
8    176565          Macbook Pro Laptop                 1  1,700.00
9    176566            Wired Headphones                 1     11.99

  Order Date      Time                        Purchase Address  \
0 2019-04-19   8:46 AM            917 1st St, Dallas, TX 75001
1 2019-04-07  10:30 PM       682 Chestnut St, Boston, MA 02215
2 2019-04-12   2:38 PM    669 Spruce St, Los Angeles, CA 90001
3 2019-04-12   2:38 PM    669 Spruce St, Los Angeles, CA 90001
4 2019-04-30   9:27 AM       333 8th St, Los Angeles, CA 90001
5 2019-04-29   1:03 PM  381 Wilson St, San Francisco, CA 94016
6 2019-04-02   7:46 AM        668 Center St, Seattle, WA 98101
7 2019-04-12  10:58 AM         790 Ridge St, Atlanta, GA 30301
8 2019-04-24  10:38 AM  915 Willow St, San Francisco, CA 94016
9 2019-04-08   2:05 PM             83 7th St, Boston, MA 02215

             City Product Type
0          Dallas        Cable
1          Boston   Headphones
2     Los Angeles        Phone
3     Los Angeles   Headphones
4     Los Angeles   Headphones
5   San Francisco        Cable
6         Seattle   Headphones
7         Atlanta        Cable
8   San Francisco       Laptop
9          Boston   Headphones

In [6]:
test_df = pd.read_csv('Sales_Product_Combined.csv')

In [9]:
conn.execute("""SELECT * FROM test_df """).df()

,Order ID,Product,Quantity Ordered,Price,Order Date,Time,Purchase Address,City,Product Type
0,176558,USB-C Charging Cable,2,11.95,19-04-2019,8:46 AM,"917 1st St, Dallas, TX 75001",Dallas,Cable
1,176559,Bose SoundSport Headphones,1,99.99,07-04-2019,10:30 PM,"682 Chestnut St, Boston, MA 02215",Boston,Headphones
2,176560,Google Phone,1,600,12-04-2019,2:38 PM,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Phone
3,176560,Wired Headphones,1,11.99,12-04-2019,2:38 PM,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,Headphones
4,176561,Wired Headphones,1,11.99,30-04-2019,9:27 AM,"333 8th St, Los Angeles, CA 90001",Los Angeles,Headphones
...,...,...,...,...,...,...,...,...,...
185945,259353,AAA Batteries (4-pack),3,2.99,17-09-2019,8:56 PM,"840 Highland St, Los Angeles, CA 90001",Los Angeles,Batteries
185946,259354,iPhone,1,700,01-09-2019,4:00 PM,"216 Dogwood St, San Francisco, CA 94016",San Francisco,iPhone
185947,259355,iPhone,1,700,23-09-2019,7:39 AM,"220 12th St, San Francisco, CA 94016",San Francisco,iPhone
185948,259356,34in Ultrawide Monitor,1,379.99,19-09-2019,5:30 PM,"511 Forest St, San Francisco, CA 94016",San Francisco,Monitor
185949,259357,USB-C Charging Cable,1,11.95,30-09-2019,12:18 AM,"250 Meadow St, San Francisco, CA 94016",San Francisco,Cable